Updated the format using the new verify-patches script.

diff --git a/atimes.diff b/atimes.diff
--- a/atimes.diff
+++ b/atimes.diff
@@ -4,8 +4,8 @@ command before "make":
     make proto
 
 
---- batch.c	15 May 2004 19:31:10 -0000	1.32
-+++ batch.c	30 Jun 2004 00:06:21 -0000
+--- orig/batch.c	2004-05-15 20:10:13
++++ batch.c	2004-07-03 20:15:41
 @@ -335,6 +335,8 @@ void show_flist(int index, struct file_s
  		rprintf(FINFO, "flist->flags=%#x\n", fptr[i]->flags);
  		rprintf(FINFO, "flist->modtime=%#lx\n",
@@ -15,8 +15,8 @@ command before "make":
  		rprintf(FINFO, "flist->length=%.0f\n",
  			(double) fptr[i]->length);
  		rprintf(FINFO, "flist->mode=%#o\n", (int) fptr[i]->mode);
---- flist.c	18 Jun 2004 16:29:21 -0000	1.231
-+++ flist.c	30 Jun 2004 00:06:21 -0000
+--- orig/flist.c	2004-06-18 16:23:07
++++ flist.c	2004-07-03 20:15:41
 @@ -58,6 +58,7 @@ extern int relative_paths;
  extern int implied_dirs;
  extern int copy_links;
@@ -128,8 +128,8 @@ command before "make":
  	file->length = st.st_size;
  	file->mode = st.st_mode;
  	file->uid = st.st_uid;
---- generator.c	29 Jun 2004 19:19:00 -0000	1.92
-+++ generator.c	30 Jun 2004 00:06:21 -0000
+--- orig/generator.c	2004-06-30 07:24:45
++++ generator.c	2004-07-03 20:15:41
 @@ -99,7 +99,7 @@ static int skip_file(char *fname, struct
  	if (ignore_times)
  		return 0;
@@ -148,8 +148,8 @@ command before "make":
  		if (verbose > 1)
  			rprintf(FINFO,"%s is newer\n",fname);
  		return;
---- options.c	20 Jun 2004 19:47:05 -0000	1.157
-+++ options.c	30 Jun 2004 00:06:21 -0000
+--- orig/options.c	2004-06-20 19:30:00
++++ options.c	2004-07-03 20:15:41
 @@ -48,6 +48,7 @@ int preserve_devices = 0;
  int preserve_uid = 0;
  int preserve_gid = 0;
@@ -183,8 +183,8 @@ command before "make":
  	if (preserve_perms)
  		argstr[x++] = 'p';
  	if (recurse)
---- rsync.c	11 Jun 2004 07:40:45 -0000	1.141
-+++ rsync.c	30 Jun 2004 00:06:22 -0000
+--- orig/rsync.c	2004-07-02 18:06:32
++++ rsync.c	2004-07-03 20:15:41
 @@ -25,6 +25,7 @@
  extern int verbose;
  extern int dry_run;
@@ -229,8 +229,8 @@ command before "make":
  	}
  
  	change_uid = am_root && preserve_uid && st->st_uid != file->uid;
---- rsync.h	16 May 2004 07:28:24 -0000	1.204
-+++ rsync.h	30 Jun 2004 00:06:22 -0000
+--- orig/rsync.h	2004-05-16 07:58:12
++++ rsync.h	2004-07-03 20:15:41
 @@ -54,6 +54,7 @@
  #define XMIT_HAS_IDEV_DATA (1<<9)
  #define XMIT_SAME_DEV (1<<10)
@@ -255,8 +255,8 @@ command before "make":
  	uid_t uid;
  	gid_t gid;
  	mode_t mode;
---- rsync.yo	5 Jun 2004 16:16:30 -0000	1.171
-+++ rsync.yo	30 Jun 2004 00:06:23 -0000
+--- orig/rsync.yo	2004-06-17 06:32:00
++++ rsync.yo	2004-07-03 20:15:41
 @@ -300,6 +300,7 @@ verb(
   -g, --group                 preserve group
   -D, --devices               preserve devices (root only)
@@ -277,8 +277,76 @@ command before "make":
  dit(bf(-n, --dry-run)) This tells rsync to not do any file transfers,
  instead it will just report the actions it would have taken.
  
---- tls.c	15 May 2004 19:09:42 -0000	1.20
-+++ tls.c	30 Jun 2004 00:06:23 -0000
+--- orig/testsuite/copy-atimes.test	2004-06-30 00:06:23
++++ testsuite/copy-atimes.test	2004-06-30 00:06:23
+@@ -0,0 +1,19 @@
++#! /bin/sh
++
++# Test rsync copying atimes
++
++. "$suitedir/rsync.fns"
++
++set -x
++
++mkdir "$fromdir"
++
++touch "$fromdir/foo"
++touch -a -t 200102031717.42 "$fromdir/foo"
++
++TLS_ARGS=--atime
++
++checkit "$RSYNC -rtAgvvv \"$fromdir/\" \"$todir/\"" "$fromdir" "$todir"
++
++# The script would have aborted on error, so getting here means we've won.
++exit 0
+--- orig/testsuite/rsync.fns	2004-06-28 21:08:14
++++ testsuite/rsync.fns	2004-07-03 20:15:41
+@@ -50,7 +50,7 @@ printmsg() {
+ 
+ 
+ rsync_ls_lR() {
+-    find "$@" -print | sort | xargs "$TOOLDIR/tls"
++    find "$@" -print | sort | xargs "$TOOLDIR/tls" $TLS_ARGS
+ }
+ 
+ rsync_getgroups() { 
+@@ -150,6 +150,8 @@ checkit() {
+     # We can just write everything to stdout/stderr, because the
+     # wrapper hides it unless there is a problem.
+ 
++    ( cd "$2" && rsync_ls_lR . ) > "$tmpdir/ls-from"
++
+     echo "Running: \"$1\""  
+     eval "$1" 
+     status=$?
+@@ -158,6 +160,12 @@ checkit() {
+     fi
+ 
+     echo "-------------"
++    echo "check how the directory listings compare with diff:"
++    echo ""
++    ( cd "$3" && rsync_ls_lR . ) > "$tmpdir/ls-to"
++    diff $diffopt "$tmpdir/ls-from" "$tmpdir/ls-to" || failed=YES
++
++    echo "-------------"
+     echo "check how the files compare with diff:"
+     echo ""
+     for f in `cd "$2"; find . -type f -print `
+@@ -165,12 +173,6 @@ checkit() {
+         diff $diffopt "$2"/"$f" "$3"/"$f" || failed=YES
+     done
+ 
+-    echo "-------------"
+-    echo "check how the directory listings compare with diff:"
+-    echo ""
+-    ( cd "$2" && rsync_ls_lR . ) > "$tmpdir/ls-from"
+-    ( cd "$3" && rsync_ls_lR . ) > "$tmpdir/ls-to"
+-    diff $diffopt "$tmpdir/ls-from" "$tmpdir/ls-to" || failed=YES
+     if [ -z "$failed" ] ; then
+ 	return 0
+     else
+--- orig/tls.c	2004-05-15 20:10:13
++++ tls.c	2004-07-03 20:15:41
 @@ -39,6 +39,7 @@
  
  
@@ -414,8 +482,8 @@ command before "make":
  
  	return 0;
  }
---- util.c	9 Jun 2004 21:51:07 -0000	1.149
-+++ util.c	30 Jun 2004 00:06:23 -0000
+--- orig/util.c	2004-06-09 21:54:47
++++ util.c	2004-07-03 20:15:41
 @@ -127,31 +127,39 @@ void overflow(char *str)
  
  
@@ -482,71 +550,3 @@ command before "make":
  {
  	if (file2 > file1) {
  		if (file2 - file1 <= modify_window)
---- /dev/null	1 Jan 1970 00:00:00 -0000
-+++ testsuite/copy-atimes.test	30 Jun 2004 00:06:23 -0000
-@@ -0,0 +1,19 @@
-+#! /bin/sh
-+
-+# Test rsync copying atimes
-+
-+. "$suitedir/rsync.fns"
-+
-+set -x
-+
-+mkdir "$fromdir"
-+
-+touch "$fromdir/foo"
-+touch -a -t 200102031717.42 "$fromdir/foo"
-+
-+TLS_ARGS=--atime
-+
-+checkit "$RSYNC -rtAgvvv \"$fromdir/\" \"$todir/\"" "$fromdir" "$todir"
-+
-+# The script would have aborted on error, so getting here means we've won.
-+exit 0
---- testsuite/rsync.fns	24 Jun 2004 04:46:02 -0000	1.61
-+++ testsuite/rsync.fns	30 Jun 2004 00:06:23 -0000
-@@ -50,7 +50,7 @@ printmsg() {
- 
- 
- rsync_ls_lR() {
--    find "$@" -print | sort | xargs "$TOOLDIR/tls"
-+    find "$@" -print | sort | xargs "$TOOLDIR/tls" $TLS_ARGS
- }
- 
- rsync_getgroups() { 
-@@ -150,6 +150,8 @@ checkit() {
-     # We can just write everything to stdout/stderr, because the
-     # wrapper hides it unless there is a problem.
- 
-+    ( cd "$2" && rsync_ls_lR . ) > "$tmpdir/ls-from"
-+
-     echo "Running: \"$1\""  
-     eval "$1" 
-     status=$?
-@@ -158,6 +160,12 @@ checkit() {
-     fi
- 
-     echo "-------------"
-+    echo "check how the directory listings compare with diff:"
-+    echo ""
-+    ( cd "$3" && rsync_ls_lR . ) > "$tmpdir/ls-to"
-+    diff $diffopt "$tmpdir/ls-from" "$tmpdir/ls-to" || failed=YES
-+
-+    echo "-------------"
-     echo "check how the files compare with diff:"
-     echo ""
-     for f in `cd "$2"; find . -type f -print `
-@@ -165,12 +173,6 @@ checkit() {
-         diff $diffopt "$2"/"$f" "$3"/"$f" || failed=YES
-     done
- 
--    echo "-------------"
--    echo "check how the directory listings compare with diff:"
--    echo ""
--    ( cd "$2" && rsync_ls_lR . ) > "$tmpdir/ls-from"
--    ( cd "$3" && rsync_ls_lR . ) > "$tmpdir/ls-to"
--    diff $diffopt "$tmpdir/ls-from" "$tmpdir/ls-to" || failed=YES
-     if [ -z "$failed" ] ; then
- 	return 0
-     else
