Fixed failing hunks.

diff --git a/dir-times.diff b/dir-times.diff
--- a/dir-times.diff
+++ b/dir-times.diff
@@ -1,5 +1,5 @@
 --- options.c	6 May 2004 21:08:01 -0000	1.148
-+++ options.c	13 May 2004 18:59:46 -0000
++++ options.c	18 May 2004 09:48:58 -0000
 @@ -46,6 +46,7 @@ int preserve_devices = 0;
  int preserve_uid = 0;
  int preserve_gid = 0;
@@ -35,8 +35,8 @@
  	if (preserve_perms)
  		argstr[x++] = 'p';
  	if (recurse)
---- rsync.c	13 May 2004 18:51:22 -0000	1.138
-+++ rsync.c	13 May 2004 18:59:47 -0000
+--- rsync.c	15 May 2004 19:31:10 -0000	1.139
++++ rsync.c	18 May 2004 09:48:58 -0000
 @@ -25,6 +25,7 @@
  extern int verbose;
  extern int dry_run;
@@ -69,7 +69,7 @@
  				full_fname(fname));
  			return 0;
 --- rsync.yo	7 May 2004 00:18:37 -0000	1.169
-+++ rsync.yo	13 May 2004 18:59:47 -0000
++++ rsync.yo	18 May 2004 09:48:58 -0000
 @@ -298,7 +298,8 @@ verb(
   -o, --owner                 preserve owner (root only)
   -g, --group                 preserve group
@@ -105,9 +105,9 @@
  
  dit(bf(-n, --dry-run)) This tells rsync to not do any file transfers,
  instead it will just report the actions it would have taken.
---- testsuite/chgrp.test	5 Feb 2004 01:37:08 -0000	1.10
-+++ testsuite/chgrp.test	13 May 2004 18:59:47 -0000
-@@ -29,7 +29,7 @@ do
+--- testsuite/chgrp.test	18 May 2004 00:41:35 -0000	1.11
++++ testsuite/chgrp.test	18 May 2004 09:48:58 -0000
+@@ -26,7 +26,7 @@ do
  done
  sleep 2
  
@@ -116,9 +116,9 @@
  
  # The script would have aborted on error, so getting here means we've won.
  exit 0
---- testsuite/chown.test	4 Feb 2004 18:24:41 -0000	1.4
-+++ testsuite/chown.test	13 May 2004 18:59:47 -0000
-@@ -31,7 +31,7 @@ chown 5001 "$name2" || test_skipped "Can
+--- testsuite/chown.test	18 May 2004 00:41:35 -0000	1.5
++++ testsuite/chown.test	18 May 2004 09:48:58 -0000
+@@ -28,7 +28,7 @@ chown 5001 "$name2" || test_skipped "Can
  chgrp 5002 "$name1" || test_skipped "Can't chgrp (probably need root)"
  chgrp 5003 "$name2" || test_skipped "Can't chgrp (probably need root)"
  
@@ -127,31 +127,37 @@
  
  # The script would have aborted on error, so getting here means we've won.
  exit 0
---- testsuite/daemon-gzip-download.test	4 Feb 2004 18:24:41 -0000	1.6
-+++ testsuite/daemon-gzip-download.test	13 May 2004 18:59:47 -0000
-@@ -27,7 +27,7 @@ RSYNC_CONNECT_PROG="$RSYNC --config=$con
- export RSYNC_CONNECT_PROG
- 
+--- testsuite/daemon-gzip-download.test	18 May 2004 00:41:51 -0000	1.7
++++ testsuite/daemon-gzip-download.test	18 May 2004 09:48:58 -0000
+@@ -29,9 +29,9 @@ export RSYNC_CONNECT_PROG
  hands_setup
--checkit "$RSYNC -avvvvz localhost::test-from/ \"$TO/\"" "$FROM" "$TO"
-+checkit "$RSYNC -advvvvz localhost::test-from/ \"$TO/\"" "$FROM" "$TO"
+ 
+ # Build chkdir with a normal rsync and an --exclude.
+-$RSYNC -av --exclude=foobar.baz "$fromdir/" "$chkdir/"
++$RSYNC -adv --exclude=foobar.baz "$fromdir/" "$chkdir/"
+ 
+-checkit "$RSYNC -avvvvz localhost::test-from/ \"$todir/\"" "$chkdir" "$todir"
++checkit "$RSYNC -advvvvz localhost::test-from/ \"$todir/\"" "$chkdir" "$todir"
  
  # The script would have aborted on error, so getting here means we've won.
  exit 0
---- testsuite/daemon-gzip-upload.test	4 Feb 2004 18:24:41 -0000	1.6
-+++ testsuite/daemon-gzip-upload.test	13 May 2004 18:59:47 -0000
-@@ -21,7 +21,7 @@ RSYNC_CONNECT_PROG="$RSYNC --config=$con
- export RSYNC_CONNECT_PROG
- 
+--- testsuite/daemon-gzip-upload.test	18 May 2004 00:41:51 -0000	1.7
++++ testsuite/daemon-gzip-upload.test	18 May 2004 09:48:58 -0000
+@@ -23,9 +23,9 @@ export RSYNC_CONNECT_PROG
  hands_setup
--checkit "$RSYNC -avvvvz \"$FROM/\" localhost::test-to/" "$FROM" "$TO"
-+checkit "$RSYNC -advvvvz \"$FROM/\" localhost::test-to/" "$FROM" "$TO"
+ 
+ # Build chkdir with a normal rsync and an --exclude.
+-$RSYNC -av --exclude=foobar.baz "$fromdir/" "$chkdir/"
++$RSYNC -adv --exclude=foobar.baz "$fromdir/" "$chkdir/"
+ 
+-checkit "$RSYNC -avvvvz \"$fromdir/\" localhost::test-to/" "$chkdir" "$todir"
++checkit "$RSYNC -advvvvz \"$fromdir/\" localhost::test-to/" "$chkdir" "$todir"
  
  # The script would have aborted on error, so getting here means we've won.
  exit 0
---- testsuite/devices.test	9 Apr 2004 00:36:45 -0000	1.7
-+++ testsuite/devices.test	13 May 2004 18:59:47 -0000
-@@ -32,7 +32,7 @@ mknod "$fromdir/block" b 42 69 || test_s
+--- testsuite/devices.test	18 May 2004 00:41:35 -0000	1.8
++++ testsuite/devices.test	18 May 2004 09:48:58 -0000
+@@ -29,7 +29,7 @@ mknod "$fromdir/block" b 42 69 || test_s
  mknod "$fromdir/block2" b 42 73 || test_skipped "Can't create block device node unless root"
  mknod "$fromdir/block3" b 105 73 || test_skipped "Can't create block device node unless root"
  
@@ -160,9 +166,9 @@
  
  # The script would have aborted on error, so getting here means we've won.
  exit 0
---- testsuite/duplicates.test	4 Feb 2004 18:24:41 -0000	1.9
-+++ testsuite/duplicates.test	13 May 2004 18:59:47 -0000
-@@ -36,7 +36,7 @@ ln -s "$name1" "$name2" || fail "can't c
+--- testsuite/duplicates.test	18 May 2004 00:41:35 -0000	1.10
++++ testsuite/duplicates.test	18 May 2004 09:48:59 -0000
+@@ -33,7 +33,7 @@ ln -s "$name1" "$name2" || fail "can't c
  
  outfile="$scratchdir/rsync.out"
  
@@ -171,9 +177,9 @@
      | tee "$outfile"
  
  # Make sure each file was only copied once...
---- testsuite/exclude.test	14 Apr 2004 20:50:32 -0000	1.5
-+++ testsuite/exclude.test	13 May 2004 18:59:47 -0000
-@@ -67,7 +67,7 @@ EOF
+--- testsuite/exclude.test	18 May 2004 00:41:38 -0000	1.6
++++ testsuite/exclude.test	18 May 2004 09:48:59 -0000
+@@ -63,7 +63,7 @@ EOF
  
  # Create the chk dir with what we expect to be excluded
  
@@ -182,7 +188,7 @@
  
  sleep 1 # Ensures that the rm commands will tweak the directory times.
  
-@@ -79,11 +79,11 @@ rm "$chkdir"/mid/for/foo/extra
+@@ -75,11 +75,11 @@ rm "$chkdir"/mid/for/foo/extra
  
  # Un-tweak the directory times in our first (weak) exclude test (though
  # it's a good test of the --existing option).
@@ -196,7 +202,7 @@
  
  # Modify the chk dir by removing cvs-ignored files and then tweaking the dir times.
  
-@@ -93,12 +93,12 @@ rm "$chkdir"/bar/down/to/foo/*.junk
+@@ -89,12 +89,12 @@ rm "$chkdir"/bar/down/to/foo/*.junk
  rm "$chkdir"/bar/down/to/home-cvs-exclude
  rm "$chkdir"/mid/one-in-one-out
  
@@ -211,35 +217,35 @@
      \"$fromdir/\" \"$todir/\"" "$chkdir" "$todir"
  
  # The script would have aborted on error, so getting here means we've won.
---- testsuite/hands.test	4 Feb 2004 18:24:41 -0000	1.12
-+++ testsuite/hands.test	13 May 2004 18:59:47 -0000
+--- testsuite/hands.test	18 May 2004 00:41:46 -0000	1.13
++++ testsuite/hands.test	18 May 2004 09:48:59 -0000
 @@ -11,19 +11,19 @@ hands_setup
  
  # Main script starts here
  
--runtest "basic operation" 'checkit "$RSYNC -av ${FROM}/ ${TO}" ${FROM}/ ${TO}'
-+runtest "basic operation" 'checkit "$RSYNC -adv ${FROM}/ ${TO}" ${FROM}/ ${TO}'
+-runtest "basic operation" 'checkit "$RSYNC -av \"$fromdir/\" \"$todir\"" "$fromdir/" "$todir"'
++runtest "basic operation" 'checkit "$RSYNC -adv \"$fromdir/\" \"$todir\"" "$fromdir/" "$todir"'
  
- ln ${FROM}/filelist ${FROM}/dir
--runtest "hard links" 'checkit "$RSYNC -avH ${FROM}/ ${TO}" ${FROM}/ ${TO}'
-+runtest "hard links" 'checkit "$RSYNC -advH ${FROM}/ ${TO}" ${FROM}/ ${TO}'
+ ln "$fromdir/filelist" "$fromdir/dir"
+-runtest "hard links" 'checkit "$RSYNC -avH \"$fromdir/\" \"$todir\"" "$fromdir/" "$todir"'
++runtest "hard links" 'checkit "$RSYNC -advH \"$fromdir/\" \"$todir\"" "$fromdir/" "$todir"'
  
- rm ${TO}/text
--runtest "one file" 'checkit "$RSYNC -avH ${FROM}/ ${TO}" ${FROM}/ ${TO}'
-+runtest "one file" 'checkit "$RSYNC -advH ${FROM}/ ${TO}" ${FROM}/ ${TO}'
+ rm "$todir/text"
+-runtest "one file" 'checkit "$RSYNC -avH \"$fromdir/\" \"$todir\"" "$fromdir/" "$todir"'
++runtest "one file" 'checkit "$RSYNC -advH \"$fromdir/\" \"$todir\"" "$fromdir/" "$todir"'
  
- echo "extra line" >> ${TO}/text
--runtest "extra data" 'checkit "$RSYNC -avH ${FROM}/ ${TO}" ${FROM}/ ${TO}'
-+runtest "extra data" 'checkit "$RSYNC -advH ${FROM}/ ${TO}" ${FROM}/ ${TO}'
+ echo "extra line" >> "$todir/text"
+-runtest "extra data" 'checkit "$RSYNC -avH \"$fromdir/\" \"$todir\"" "$fromdir/" "$todir"'
++runtest "extra data" 'checkit "$RSYNC -advH \"$fromdir/\" \"$todir\"" "$fromdir/" "$todir"'
  
- cp ${FROM}/text ${TO}/ThisShouldGo
--runtest " --delete" 'checkit "$RSYNC --delete -avH ${FROM}/ ${TO}" ${FROM}/ ${TO}'
-+runtest " --delete" 'checkit "$RSYNC --delete -advH ${FROM}/ ${TO}" ${FROM}/ ${TO}'
+ cp "$fromdir/text" "$todir/ThisShouldGo"
+-runtest " --delete" 'checkit "$RSYNC --delete -avH \"$fromdir/\" \"$todir\"" "$fromdir/" "$todir"'
++runtest " --delete" 'checkit "$RSYNC --delete -advH \"$fromdir/\" \"$todir\"" "$fromdir/" "$todir"'
  
  # The script would have aborted on error, so getting here means we've won.
  exit 0
---- testsuite/hardlinks.test	4 Feb 2004 18:24:41 -0000	1.4
-+++ testsuite/hardlinks.test	13 May 2004 18:59:47 -0000
+--- testsuite/hardlinks.test	18 May 2004 00:41:40 -0000	1.5
++++ testsuite/hardlinks.test	18 May 2004 09:48:59 -0000
 @@ -31,7 +31,7 @@ ln "$name1" "$name2" || fail "Can't crea
  ln "$name2" "$name3" || fail "Can't create hardlink"
  cp "$name2" "$name4" || fail "Can't copy file"
@@ -249,20 +255,20 @@
  
  # The script would have aborted on error, so getting here means we've won.
  exit 0
---- testsuite/longdir.test	4 Feb 2004 18:24:41 -0000	1.9
-+++ testsuite/longdir.test	13 May 2004 18:59:47 -0000
-@@ -18,7 +18,7 @@ makepath $LONGDIR || test_skipped "unabl
- touch $LONGDIR/1 || test_skipped "unable to create files in long directory"
- date > ${LONGDIR}/1
- ls -la / > ${LONGDIR}/2
--checkit "$RSYNC --delete -avH ${FROM}/ ${TO}" ${FROM}/ ${TO}
-+checkit "$RSYNC --delete -advH ${FROM}/ ${TO}" ${FROM}/ ${TO}
+--- testsuite/longdir.test	18 May 2004 09:47:42 -0000	1.11
++++ testsuite/longdir.test	18 May 2004 09:48:59 -0000
+@@ -18,7 +18,7 @@ makepath "$longdir" || test_skipped "una
+ touch "$longdir/1" || test_skipped "unable to create files in long directory"
+ date > "$longdir/1"
+ ls -la / > "$longdir/2"
+-checkit "$RSYNC --delete -avH \"$fromdir/\" \"$todir\"" "$fromdir/" "$todir"
++checkit "$RSYNC --delete -advH \"$fromdir/\" \"$todir\"" "$fromdir/" "$todir"
  
  # The script would have aborted on error, so getting here means we've won.
  exit 0
---- testsuite/merge.test	30 Apr 2004 17:24:49 -0000	1.5
-+++ testsuite/merge.test	13 May 2004 18:59:47 -0000
-@@ -43,9 +43,9 @@ cp -p "$from2dir"/sub1/uno "$from3dir"/s
+--- testsuite/merge.test	18 May 2004 00:41:38 -0000	1.6
++++ testsuite/merge.test	18 May 2004 09:48:59 -0000
+@@ -40,9 +40,9 @@ cp -p "$from2dir"/sub1/uno "$from3dir"/s
  cp -p "$from3dir"/sub2/subby "$chkdir"/sub2
  
  # Get rid of any directory-time differences
@@ -274,25 +280,25 @@
  
  # The script would have aborted on error, so getting here means we've won.
  exit 0
---- testsuite/ssh-basic.test	19 Feb 2003 16:22:50 -0000	1.6
-+++ testsuite/ssh-basic.test	13 May 2004 18:59:47 -0000
+--- testsuite/ssh-basic.test	18 May 2004 00:41:46 -0000	1.7
++++ testsuite/ssh-basic.test	18 May 2004 09:48:59 -0000
 @@ -28,7 +28,7 @@ fi
  # nothing to do.
  hands_setup
  
--runtest "ssh: basic test" 'checkit "$RSYNC -avH -e ssh --rsync-path=$RSYNC ${FROM}/ localhost:${TO}" ${FROM}/ ${TO}'
-+runtest "ssh: basic test" 'checkit "$RSYNC -advH -e ssh --rsync-path=$RSYNC ${FROM}/ localhost:${TO}" ${FROM}/ ${TO}'
+-runtest "ssh: basic test" 'checkit "$RSYNC -avH -e ssh --rsync-path=$RSYNC \"$fromdir/\" \"localhost:$todir\"" "$fromdir/" "$todir"'
++runtest "ssh: basic test" 'checkit "$RSYNC -advH -e ssh --rsync-path=$RSYNC \"$fromdir/\" \"localhost:$todir\"" "$fromdir/" "$todir"'
  
  # Added by Steve Bonds Feb 2 2003
  # I assumed that "F1" was intended to hold a single file for testing if
-@@ -40,4 +40,4 @@ F1=`ls ${TO} | head -5 | tail -1`
+@@ -40,4 +40,4 @@ F1=`ls "$todir" | head -5 | tail -1`
  
- mv ${TO}/${F1} ${TO}/ThisShouldGo
+ mv "$todir/$F1" "$todir/ThisShouldGo"
  
--runtest "ssh: renamed file" 'checkit "$RSYNC --delete -avH -e ssh --rsync-path=$RSYNC ${FROM}/ localhost:${TO}" ${FROM}/ ${TO}'
-+runtest "ssh: renamed file" 'checkit "$RSYNC --delete -advH -e ssh --rsync-path=$RSYNC ${FROM}/ localhost:${TO}" ${FROM}/ ${TO}'
---- testsuite/unsafe-links.test	15 Jan 2003 16:14:07 -0000	1.6
-+++ testsuite/unsafe-links.test	13 May 2004 18:59:47 -0000
+-runtest "ssh: renamed file" 'checkit "$RSYNC --delete -avH -e ssh --rsync-path=$RSYNC \"$fromdir/\" \"localhost:$todir\"" "$fromdir/" "$todir"'
++runtest "ssh: renamed file" 'checkit "$RSYNC --delete -advH -e ssh --rsync-path=$RSYNC \"$fromdir/\" \"localhost:$todir\"" "$fromdir/" "$todir"'
+--- testsuite/unsafe-links.test	18 May 2004 00:41:43 -0000	1.7
++++ testsuite/unsafe-links.test	18 May 2004 09:48:59 -0000
 @@ -35,33 +35,33 @@ ln -s ../../unsafe/unsafefile "from/safe
  set -x
  
